version: "3"
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/opt/projects
    tty: true
    stdin_open: true
  #   depends_on:
  #     - db

  # db:
  #   image: mysql:5.7
  #   environment:
  #   - MYSQL_DATABASE=test_db
  #   - MYSQL_ROOT_PASSWORD=password
  #   command: >
  #     --character-set-server=utf8mb4
  #     --collation-server=utf8mb4_general_ci
  #     --innodb_file_per_table
  #     --innodb_file_format=BARRACUDA
  #     --innodb_large_prefix=1
  #   ports:
  #     - 3306:3306